apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-apps"
    spec:
      project: "cluster-{{name}}"
      source:
        repoURL: https://github.com/larsks/kind-cluster.git
        targetRevision: HEAD
        path: "./clusters/{{name}}/apps"
      destination:
        server: https://kubernetes.default.svc
        namespace: "argocd"
