apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- apps

nameSuffix: -infra

components:
- ../../components/standard_repo_url
- ../../components/standard_sync_policy

patches:
  - patch: |
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: root
        namespace: argocd
      spec:
        source:
          path: argocd/overlays/infra

  - patch: |
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: cert-manager
        namespace: argocd
      spec:
        source:
          path: apps/cert-manager/overlays/infra
