apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-certificates
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/larsks/kind-cluster.git
    targetRevision: HEAD
    path: ./apps/step-certificates/overlays/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: step-certificates
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
