apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secrets-reader
            namespace: cluster-secrets
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: aws-secrets-reader
            namespace: cluster-secrets
            key: AWS_SECRET_ACCESS_KEY
