- hosts: localhost
  gather_facts: false
  tasks:
    - name: create clusters
      include_role:
        name: kind-cluster
      loop: "{{ clusters }}"
      loop_control:
        loop_var: cluster

    - name: get infra cluster info
      set_fact:
        infra_cluster: "{{ clusters | selectattr('name', 'eq', 'infra') | first }}"

    - name: bootstrap argocd
      tags: [argocd]
      include_role:
        name: argocd
        apply:
          tags: [argocd]
      vars:
        cluster: "{{ infra_cluster }}"

    - name: install aws credentials
      tags: [secrets]
      include_role:
        name: cluster_secrets
        apply:
          tags: [secrets]
      vars:
        cluster: "{{ infra_cluster }}"

    - name: deploy root app
      tags: [apps]
      k8s:
        state: present
        kustomize: "clusters/{{ infra_cluster.name }}-kubeconfig.yaml"
        definition: >-
          {{ lookup("kubernetes.core.kustomize", dir="argocd/overlays/in-cluster") }}

