apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-ingress

commonLabels:
  app.kubernetes.io/name: traefik
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - traefik.yaml
