apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - target:
      kind: Application
    patch: |
      - op: remove
        path: /spec/destination/server
      - op: add
        path: /spec/destination/name
        value: cluster2
      - op: replace
        path: /spec/project
        value: cluster-cluster2

nameSuffix: -cluster2
