apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../common

patches:
  - patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: step-certificates
        annotations:
          cert-manager.io/cluster-issuer: in-cluster

