apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
  data:
    - secretKey: discord-webhook-url
      remoteRef:
        key: house/argocd/discord-webhook-url
        property: url
