apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ../bootstrap
  - resources/clusters
  - resources/externalsecrets
  - resources/ingresses

generatorOptions:
  disableNameSuffixHash: true
