apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPOURL
    targetRevision: HEAD
    path: apps/nginx-ingress/overlays/common
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
