apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Application
      name: ".*"
    patch: |
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: ignored
      spec:
        source:
          repoURL: https://github.com/larsks/kind-cluster
          targetRevision: ansible
