apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPOURL
    targetRevision: HEAD
    path: apps/argocd/overlays/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
