apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPOURL
    targetRevision: HEAD
    path: apps/awx/overlays/common
  destination:
    server: https://kubernetes.default.svc
    namespace: awx-operator
