apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-certificates
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPOURL
    targetRevision: HEAD
    path: apps/step-certificates/overlays/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: step-certificates
