apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: house
spec:
  acme:
    server: https://ca.apps.infra.house/acme/acme/directory
    privateKeySecretRef:
      name: house-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
