apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-cluster2
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: "https://192.168.1.202:6443"
  sourceRepos:
  - '*'
status: {}
