apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/larsks/kind-cluster.git
    targetRevision: develop
    path: lib/olm/overlays/default
  destination:
    server: https://kubernetes.default.svc
    namespace: olm
