
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: olm
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            oddbit.com/olm: "true"
  template:
    metadata:
      name: "olm-{{name}}"
    spec:
      project: cluster-{{name}}
      source:
        repoURL: https://github.com/larsks/kind-cluster.git
        targetRevision: HEAD
        path: ./apps/olm/overlays/common
      destination:
        server: "{{server}}"
        namespace: olm
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
