apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  # Enable argocd web terminal
  - path: clusterroles/argocd-server_patch.yaml
    target:
      kind: ClusterRole
      name: argocd-server

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    files:
      # Enable web terminal
      - configs/argocd/exec.enabled

generatorOptions:
  disableNameSuffixHash: true
