apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            oddbit.com/services: "true"
            oddbit.com/ingress: "nginx"
  template:
    metadata:
      name: "{{name}}-cert-manager"
    spec:
      project: "cluster-{{name}}"
      source:
        repoURL: https://github.com/larsks/kind-cluster.git
        targetRevision: HEAD
        path: "./apps/cert-manager/overlays/{{name}}"
      destination:
        server: "{{server}}"
        namespace: "cert-manager"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
