apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            oddbit.com/services: "true"
  template:
    metadata:
      name: "{{name}}-external-secrets"
    spec:
      project: "cluster-{{name}}"
      source:
        repoURL: https://github.com/larsks/kind-cluster.git
        targetRevision: HEAD
        path: "./apps/external-secrets/overlays/{{name}}"
      destination:
        server: "{{server}}"
        namespace: "external-secrets"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
