apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resources/apps
  - resources/applicationsets

patches:
  - target:
      kind: Application
      name: cert-manager
    patch: |
      - op: replace
        path: /spec/source/path
        value: ./apps/cert-manager/overlays/infra

  - target:
      kind: Application
      name: ".*"
    patch: |
      - op: replace
        path: /spec/project
        value: cluster-infra

nameSuffix: -infra
