apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: step-certificates

commonLabels:
  app.kubernetes.io/name: step-certificates
  app.kubernetes.io/instance: changeme
  app.kubernetes.io/managed-by: kustomize

resources:
- namespace.yaml
- step-certificates.yaml
