inject:
  enabled: true
  config:
    files:
      ca.json:
        root: /home/step/certs/root_ca.crt
        federateRoots: []
        crt: /home/step/certs/intermediate_ca.crt
        key: /home/step/secrets/intermediate_ca_key
        address: :9000
        dnsNames:
          - localhost
        logger:
          format: json
        db:
          type: badgerv2
          dataSource: /home/step/db
        authority:
          provisioners: []
        tls:
          cipherSuites:
            - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          minVersion: 1.2
          maxVersion: 1.3
          renegotiation: false
      defaults.json:
        ca-url: https://localhost
        ca-config: /home/step/config/ca.json
        fingerprint: ROOT CA FINGERPRINT
        root: /home/step/certs/root_ca.crt
  certificates:
    intermediate_ca: INTERMEDIATE CA CERT
    root_ca: ROOT CA CERT
  secrets:
    ca_password: SECRET
    provisioner_password: SECRET
    x509:
      intermediate_ca_key: INTERMEDIATE CA KEY
      root_ca_key: ROOT CA KEY
