apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-cluster-apps"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/larsks/kind-cluster.git
        targetRevision: HEAD
        path: "clusters/overlays/{{name}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
