apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-admin-password
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    name: awx-admin-password
  data:
    - secretKey: password
      remoteRef:
        key: house/awx-operator/awx-admin-password
