apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami

commonLabels:
  app.kubernetes.io/name: whoami

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
