apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
- apps

nameSuffix: -infra

patches:
  - target:
      kind: Application
      name: ".*"
    patch: |
      - op: add
        path: /spec/syncPolicy
        value:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
            - CreateNamespace=true

